export {ReactComponent as Logo} from '../assets/imgs/logo.svg'
export {ReactComponent as Home} from '../assets/imgs/home.svg'
export {ReactComponent as HomeActive} from '../assets/imgs/home-active.svg'
export {ReactComponent as Search} from '../assets/imgs/search.svg'
export {ReactComponent as SearchActive} from '../assets/imgs/search-active.svg'
export {ReactComponent as Library} from '../assets/imgs/library.svg'
export {ReactComponent as LibraryActive} from '../assets/imgs/library-active.svg'
export {ReactComponent as PlayIcon} from '../assets/imgs/play.svg'
export {ReactComponent as PauseIcon} from '../assets/imgs/pause.svg'
export {ReactComponent as CreatePlaylists} from '../assets/imgs/create-playlists.svg'
export {ReactComponent as LikedSongs} from '../assets/imgs/liked-songs.svg'
export {ReactComponent as PlayNextIcon} from '../assets/imgs/play-next.svg'
export {ReactComponent as PlayPrevIcon} from '../assets/imgs/play-prev.svg'

