
export { ReactComponent as Logo } from '../assets/imgs/logo.svg'
export { ReactComponent as HomeIcon } from '../assets/imgs/home.svg'
export { ReactComponent as HomeActiveIcon } from '../assets/imgs/home-active.svg'
export { ReactComponent as SearchIcon } from '../assets/imgs/search.svg'
export { ReactComponent as SearchActiveIcon } from '../assets/imgs/search-active.svg'
export { ReactComponent as LibraryIcon } from '../assets/imgs/library.svg'
export { ReactComponent as LibraryActiveIcon } from '../assets/imgs/library-active.svg'
export { ReactComponent as PlayIcon } from '../assets/imgs/play.svg'
export { ReactComponent as PauseIcon } from '../assets/imgs/pause.svg'
export { ReactComponent as CreatePlaylistsIcon } from '../assets/imgs/create-playlists.svg'
export { ReactComponent as LikedSongsIcon } from '../assets/imgs/liked-songs.svg'
export { ReactComponent as PlayNextIcon } from '../assets/imgs/play-next.svg'
export { ReactComponent as PlayPrevIcon } from '../assets/imgs/play-prev.svg'
export { ReactComponent as SearchBarIcon } from '../assets/imgs/search-bar.svg'
export { ReactComponent as VolumeIcon } from '../assets/imgs/volume.svg'
export { ReactComponent as VolumeMuteIcon } from '../assets/imgs/volume-mute.svg'

